### ISSUE TITLE
inconsistent content between EN and DE

### ISSUE THREAD

**Issue by netapp-ehoffman** [NetAppDocs/ontap.de-de#1]
### Page URL

https://docs.netapp.com/de-de/ontap/mediator/index.html

### Page title

Bereiten Sie die Installation oder das Upgrade des ONTAP Mediatordienstes vor

### Summary

It's been observed that the ENG and German content for this page is out of sync. See the supported Linux versions for ONTAP Mediator 1.6.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by ntap-bmegan** [comment]
From the email:

the documentation of Mediator (for RHEL 8.8.) is different in the english version and the german version.

english:
https://docs.netapp.com/us-en/ontap/mediator/index.html

![image](https://github.com/NetAppDocs/ontap.de-de/assets/56453501/c8592924-ea1e-420a-af16-18669112cef5)

german:
https://docs.netapp.com/de-de/ontap/mediator/index.html

![image](https://github.com/NetAppDocs/ontap.de-de/assets/56453501/fbce7446-74a2-4dce-b43f-bb65d1c7a391)

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - Can you check on this? I'm not sure if it's just a matter of deleting the DE dictionary to see if we get the correct string back, or if you'll need to have the memory cleared out. I haven't checked the other languages.

**Comment by netapp-gudugunti** [comment]
@ntap-bmegan There are issues in other languages as well. Have opened an internal ticket for further discussion.

**Comment by netapp-gudugunti** [comment]
Thanks! for reporting the problem, @netapp-ehoffman.
The matter about inconsistent versions has been resolved.
Closing the issue.
